### ISSUE TITLE
XML error

### ISSUE THREAD

**Issue by snipercommando** [Shadez/wowarmory#110]
I have uploadet the page change config file adn setup db but when i try do acces the armory i got this error

The XML input can not be displayed when using XSL style sheet.

**Comment by Shadez** [comment]
What? More informative, please.

**Comment by devil1234** [comment]
appear on http://localhost/armory/item-search.xml when you try to open the advanced search

**Comment by soar** [comment]
For me, FF3 and Opera works fine, but IE and Chrome - not. IE doesn't render any page at all and says about unsupported encoding. Chrome - works, but not show text in tooltips ("Loading..." and then - nothing) and can't open pages character-talents.xml (talent-calc.xml - works) and character-achievements.xml.

**Comment by Shadez** [comment]
<b>soar</b>, layout bugs in IE browser is my headache. I know a lot about PHP stuff but my knowledges about CSS/JavaScript is so poor and usualy I can't handle any of layout-related errors. If there's somebody who can look into it more deeper, it will be so nice but I can't say you anything about these issues.

**Comment by duergar85** [comment]
IE 7 and 8 works pretty well with the Armory (I use the en-gb language) while I'm not sure about IE 6 or lower.
About Chrome, I think that it has a bundled AD-blocker that was my problem with FF3, if you can deactivate it for localhost, maybe tooltips and talents could work.

About the XML error, try to delete totally your browser and Armory cache.

I also find that sometimes the problem is IIS (if you are on Windows and not using Apache) and that executing the following command can be helpful:
%windir%\Microsoft.NET\Framework\v2.0.50727\aspnet_regiis.exe -i
I'm not sure it will be of any help,tho.
