### ISSUE TITLE
Item info

### ISSUE THREAD

**Issue by Muglackh** [Shadez/wowarmory#133]
Hello, before I will post an issue, I thank you for great work!
So, I have a problem: some items (gems and enchants) have no tooltip (on mouseover) in characters view. They are no entry in DB, I think. Have you any update for those items? 

So, implement Wowhead support into Armory is other way to show tooltips. Shadez, please, it is a good idea?

**Comment by Shadez** [comment]
You should ask your DB provider for updates, not me. As far as I know YTDB & UDB have all 3.3.5a items.
About Wowhead tooltips: I don't think that this is a good idea because of 3 reasons:
1) item-info.xml page requires data from item-template.xml page.
2) It's a wrong way to implement some features by using 3-rd party sites.
3) Tooltips have full implementation and it works as intended in 99.9% cases (0.1% - is case like your - when item is not in DB).
