### ISSUE TITLE
Little roblems with 351

### ISSUE THREAD

**Issue by Vasago** [Shadez/wowarmory#58]
There are three problems now:
1) Sets like gladiators are not visible - just still grey like i have 0/5 but i have 5/5 maybe also in others sets
2) Spell power is showed like Bonus Healing: ahould be also in Bonus Damage:
3) When there are missing models in viewer 3D can i somehow reextract images from client? And if yes - how and where I can get some tools? Thx

**Comment by Shadez** [comment]
1) Already in my todo list. Need itemsets data for table `armory_itemsetdata`.
2) Fixed in 352 rev.
3) Yes, you can. They're stored in "Item" folder of all MPQ archives (data/*.mpq). For extracting you can try Total Commander plugin (http://www.totalcmd.net/plugring/mpq.html). Also, you'll need BLP to PNG converter (I recommend BLP2PNG (http://www.wowinterface.com/downloads/info6127-BLP2PNG.html)).

**Comment by Vasago** [comment]
1) Trynity has a special table for it item_set_names if it helps
2) Thanks
3) I tried plugin and it works ... also i tried to find missing files but no success like:
File does not exist: /models/item/objectcomponents/shield/axe_1h_northrend_b_01.m2
File does not exist: /models/item/objectcomponents/shield/axe_1h_northrend_b_01.jpg
File does not exist: /models/item/objectcomponents/shield/axe_1h_northrend_b_01.png
plate_pvpwarrior_b_04_glove_al_u.jpg
plate_pvpwarrior_b_04_glove_al_u.png
So there are not only png files missing
I tried to search axe_1h_northrend_b_01\* not result

Here are some errors in debug:
ArmoryDatabaseHandler::_query : unable to execute SQL query (SELECT `durability` FROM `item_instance` WHERE `owner_guid`=2222 AND `item_template`=51378). MySQL error: none
ArmoryDatabaseHandler::_query : unable to execute SQL query (SELECT `gmlevel` FROM `account` WHERE `id`=200 LIMIT 1). MySQL error: none<br />
